### ISSUE TITLE
Don't do slugify in JavaScript

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/canonicalwebteam.blog#130]
See here: https://github.com/canonical-web-and-design/maas.io/pull/418#pullrequestreview-331956028

**Comment by steverydz** [comment]
This won't be necessary as the slug is already provided by the api: https://github.com/canonical-web-and-design/canonicalwebteam.blog/blob/master/canonicalwebteam/blog/feeds.py#L23
