### ISSUE TITLE
"/topic/<slug>" causing 500s on ubuntu.com

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/canonicalwebteam.blog#156]
Do we need these endpoints at all?

https://sentry.is.canonical.com/canonical/ubuntu-com/issues/10871/?query=is%3Aunresolved

Maybe we should remove the  `/topic` rules?

**Comment by SirSamTumless** [comment]
@nottrobin Could you please triage this?

**Comment by nottrobin** [comment]
Yeah I'll just do it

**Comment by sowasred2012** [comment]
@nottrobin was this done? It looks like the error stopped happening right around the time of your last comment so I'm inclined to think it was, and close this issue.

**Comment by nottrobin** [comment]
Yeah I seem to remember fixing this. Let's close it.
