### ISSUE TITLE
Restructure: Flask-only, remove blueprint factory

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/canonicalwebteam.blog#2]
Remove this function: https://github.com/canonical-web-and-design/canonicalwebteam.blog/blob/master/canonicalwebteam/blog/flask.py#L4

Remove the "flask.py", as we should no longer need Django support.

Make except logic code more semantic:
https://github.com/canonical-web-and-design/canonicalwebteam.blog/blob/master/canonicalwebteam/blog/logic.py#L78-L90

Improve Cloudinary regex - replace with BeautifulSoup or something?
https://github.com/tbille/blog-flask-extension/blob/187c88dd0959301eaad3eb67f2b333dddd2f0635/canonicalwebteam/blog_extension/logic.py#L19-L49

**Comment by carkod** [comment]
Cloudinary tasks addressed. The other 3 were address in (Mahoosive restructure)[https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/138]
