### ISSUE TITLE
Extend logic.transform_article to support expanding groups and categories

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/canonicalwebteam.blog#21]
See: https://github.com/canonical-webteam/blog/pull/19/files#r270245307

**Comment by tbille** [comment]
@b-m-f can you close it if done?

**Comment by nottrobin** [comment]
This wasn't done as part of #19 - https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/19/files#r270245307. So I guess this should remain open. @b-m-f can confirm.

**Comment by tbille** [comment]
Seems to be done.
