### ISSUE TITLE
Code structure: Can Cloudinary Regex be improved or replaced?

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/canonicalwebteam.blog#3]
https://github.com/tbille/blog-flask-extension/blob/187c88dd0959301eaad3eb67f2b333dddd2f0635/canonicalwebteam/blog_extension/logic.py#L27-L49

1. Ensure that the regex is not too greedy. It might be worth uaing BeautifulSoup instead of Regex.
2. Even if we use Regex, might it be possible to make the code slightly more semtantic, maybe:

``` python3
    image_prefix = cloudinary + "canonical/image/fetch/q_auto,f_auto"

    image_match = (
        r'<img(?P<prefix>[^>]*) src="(?P<url>[^"]+)"(?P<suffix>[^>]*)>'
    )
    replacement = (
        "<img\g<prefix>"
        f' decoding="async"'
        f' src="{image_prefix},w_350"'
        f' srcset={image_prefix},w_350 350w, {image_prefix},w_650 650w,'
        f' {image_prefix},w_1300 1300w, {image_prefix},w_1950 1950w"'
        f' sizes="(max-width: 400px) 350w, 650px"'
        "\g<suffix>>"
    )
```

**Comment by tbille** [comment]
is this still valid?

**Comment by nottrobin** [comment]
Rolled into https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/2
