### ISSUE TITLE
Add back setup.py, for now

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/canonicalwebteam.blog#37]
From https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/34#issuecomment-488238631:

> The way I would normally test this is by doing something like `pip install -e ../canonicalwebteam.blog`, or adding `-e ../canonicalwebteam.blog` or `git+git@github.com:org/canonicalwebteam.blog#egg=canonicalwebteam.blog` into `requirements.txt`.
> 
> All of these workflows are impossible without a `setup.py`.
> 
> I suspect, once we've moved all our projects over to Poetry then this problem will go away (we'll no longer be doing `pip install` anywhere), but until then, I think we should probably preserve `setup.py` so as to enable these workflows. We'll just have to make sure we do version updates etc. in both places.

**Comment by jpmartinspt** [comment]
Makes sense, maybe we can make use of https://pypi.org/project/poetry-setup/ and do it as a build step?

**Comment by b-m-f** [comment]
https://github.com/sdispater/poetry/issues/554
`poetry  add --git https://github.com/rominf/aioify.git aioify`

This should also work :)

**Comment by b-m-f** [comment]
Poetry will also automatically create a `setup.py` when running `poetry build`. It will be in the `dist` package though.

**Comment by nottrobin** [comment]
> `poetry add --git https://github.com/rominf/aioify.git aioify`

Surely this will `add` that git repository to a local `pyproject.toml` won't it? If the local project doesn't have a `pyproject.toml` this what will happen? Will it create one? 'cos that's probably not ideal either.

And of course there'd be no way with our current infrastructure to create a branch of a project that still uses `requirements.txt` that could be simply run with `./run`.

> Poetry will also automatically create a `setup.py` when running `poetry build`. It will be in the `dist` package though.

I assume this doesn't achieve the same thing as `pip install -e {path}`, because it look like it requires you to `poetry build` and then reinstall from the built package after every change.

Also, while almost all our projects are using `pip` rather than `poetry`, devs are unlikely to have `poetry` installed locally.

I do think we need `setup.py` for the time being, and we need it to be committed. But we could create a build endpoint to regenerate it from `pyproject.toml` using https://pypi.org/project/poetry-setup/.

**Comment by tbille** [comment]
@b-m-f can you reply and close if needs update?

**Comment by tbille** [comment]
This is done.
