### ISSUE TITLE
Exclude tags should work for /feed as well

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/canonicalwebteam.blog#49]
the rss feed isn't:

1. automatically excluding the language tag ids that each site sets on the rss feeds
2. it doesn't pass through tag parameters the user might request

the code should

1. automatically apply the sites (e.g. https://admin.insights.ubuntu.com/feed?tags=-3184,-3265)
2. pass through any user added tag parameters appended to the exclude list

see https://wordpress.org/support/article/wordpress-feeds/

I think we have to leave admin.insights.ubuntu.com/feeds alone to allow china, japan and blog to work

**Comment by pmahnke** [comment]
also see https://github.com/canonical-web-and-design/blog.ubuntu.com/issues/496

**Comment by b-m-f** [comment]
I did some more research on this.
Only categories can be excluded from the feed directly.

There are 2 ways to proceed:

## Add new categories to Wordpress
We can add new categories to every Post in WP that is either in Japanese or Chinese

## Add more logic to blog
We can try to exclude all foreign language content on the blog directly.
This might lead to smaller feeds.

**Comment by b-m-f** [comment]
https://github.com/canonical-web-and-design/blog.ubuntu.com/pull/533 Implents the second solution.

Since this is needed quickly but looses content and thus is the technically inferior solution, we should opt for the first one here.

@nottrobin Who should we contact to get a workflow change rolling?

**Comment by b-m-f** [comment]
If we can not change to categories we can remove the foreign content in memory by 
filtering with:
```python
def _filter_cn_jp_feeds(item):
    if "category" in item:
        for category in item["category"]:
            if "lang:cn" in category or "lang:jp" in category:
                return False
    return True


feed["rss"]["channel"]["item"] = [
    feed
    for feed in feed["rss"]["channel"]["item"]
    if _filter_cn_jp_feeds(feed)
]
```
@jpmartinspt  came up with this filter at https://pastebin.canonical.com/p/jwGy7jd3QR/

**Comment by nottrobin** [comment]
@b-m-f I think we should definitely go with the first solution here - changing to categories. We just need to let Thibaut know. @pmahnke could you facilitate this discussion please?

**Comment by b-m-f** [comment]
Fixed in https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/105
