### ISSUE TITLE
Code structure: Simplify excerpt parsing

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/canonicalwebteam.blog#5]
https://github.com/tbille/blog-flask-extension/blob/187c88dd0959301eaad3eb67f2b333dddd2f0635/canonicalwebteam/blog_extension/logic.py#L77-L89

- Explore the `+` vs `join` question - `+` is more semantic, is `join` really significantly more performant to justify it?
- Could the whole block be replaced by a simple `re.sub` line?

**Comment by tbille** [comment]
is this still valid?

**Comment by nottrobin** [comment]
Rolled into https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/2
